In [2]:
import numpy as np
import pickle
import pathlib

from os.path import join
path_to_file = str(pathlib.Path().resolve())
dir_path = join(path_to_file, "../../")
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append(join(dir_path, "HelperFiles"))
from load_data import *


In [5]:
method = "lime"
dataset = "breast_cancer"
K = 3
fname = method + "_" + dataset + "_K" + str(K) + "_fwers"
with open(join(dir_path, "Experiments", "Results", "alpha0.2", fname), "rb") as fp:
        fwers_dict = pickle.load(fp)
fwers = np.array(list(fwers_dict.values()))
np.round(fwers*100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
methods = ["shap", "lime"]
Ks = [3, 7]
datasets = ["bank", "brca", "breast_cancer", "census", "credit"]

method = methods[0]
avg_mat = np.empty((len(Ks), len(datasets)))
control_mat = np.empty((len(Ks), len(datasets)))
for i, K in enumerate(Ks):
    for j, dataset in enumerate(datasets):
        fname = method + "_" + dataset + "_K" + str(K) + "_fwers"
        with open(join(dir_path, "Experiments", "Results", "alpha0.2", fname), "rb") as fp:
                fwers_dict = pickle.load(fp)
        fwers = np.array(list(fwers_dict.values()))
        avg_fwer = np.mean(fwers)
        avg_mat[i, j] = np.round(avg_fwer*100)
        prop_fwer_control = np.mean(fwers < 0.2)
        control_mat[i, j] = prop_fwer_control #np.round(prop_fwer_control*100)


# import pandas as pd
# pd.DataFrame(avg_mat).astype('Int64')
print(method.upper())
print("Average FWER")
print(avg_mat)
print("Proportion of FWERs below alpha")
print(control_mat)

SHAP
Average FWER
[[ 6.  1.  3.  2.  1.]
 [ 3.  7. 10. 14.  6.]]
Proportion of FWERs below alpha
[[1.  1.  1.  1.  1. ]
 [1.  0.9 0.8 0.8 1. ]]


In [8]:
for dataset in datasets:
    X_train, y_train, X_test, y_test, mapping_dict = load_data(join(dir_path, "Experiments", "Data"), dataset)
    N = y_train.shape[0] + y_test.shape[0]
    D = X_train.shape[1] if mapping_dict is None else len(mapping_dict)
    print(dataset)
    print(N, D)



bank
45211 16
brca
572 20
breast_cancer
569 30
census
32561 12
credit
1000 20
