In [1]:
import numpy as np
import pickle
import pathlib
from matplotlib.ticker import ScalarFormatter
import matplotlib.pyplot as plt

import os
from os.path import join
path_to_file = str(pathlib.Path().resolve())
dir_path = join(path_to_file, "../../")
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append(join(dir_path, "HelperFiles"))
from load_data import *


In [4]:

# alpha = 0.2
# # alpha = 0.1

# # guarantee = "rank"
# guarantee = "set"

datasets = ["census", "bank", "brca", "breast_cancer", "credit"]
Ks = [2,5]
# method = "rankshap"
# method = "sprtshap"
for method in ["rankshap", "sprtshap"]:
    for guarantee in ["rank", "set"]:
        for alpha in [0.1, 0.2]:
            avg_mat = np.empty((len(Ks), len(datasets)))
            control_mat = np.empty((len(Ks), len(datasets)))
            max_mat = np.empty((len(Ks), len(datasets)))
            data_dir = join(dir_path, "Experiments", "Results", "Top_K", guarantee, "alpha_"+str(alpha))
            for i, K in enumerate(Ks):
                for j, dataset in enumerate(datasets):
                    avg_mat[i, j] = np.nan
                    control_mat[i, j] = np.nan
                    max_mat[i,j] = np.nan
                    fname = method + "_" + dataset + "_K" + str(K) 
                    path = join(data_dir, fname)
                    if os.path.exists(path):
                        with open(path, "rb") as fp:
                            results = pickle.load(fp)
                        fwers = results['fwers']
                        # num_non_na = np.count_nonzero(~np.isnan(fwers))
                        # if num_non_na < 30:
                        #     print("Still sampling for ", fname)
                        avg_fwer = np.mean(fwers)
                        max_fwer = np.max(fwers)
                        max_mat[i, j] = np.round(max_fwer*100, 1)
                        avg_mat[i, j] = np.round(avg_fwer*100, 1)
                        # prop_fwer_control = np.mean(fwers < alpha)
                        # control_mat[i, j] = prop_fwer_control
                    else:
                        print("File not found: ", fname)
            print("#"*20)
            print("Method: ", method, "\tGuarantee: ", guarantee, "\tAlpha: ", alpha)

            # print("Average FWER (%)")
            # print(avg_mat)
            print("Max FWER (%)")
            print(max_mat)
            # print("Proportion of FWERs below alpha")
            # print(control_mat)


File not found:  rankshap_breast_cancer_K5
####################
Method:  rankshap 	Guarantee:  rank 	Alpha:  0.1
Max FWER (%)
[[ 2.  6.  4.  0.  4.]
 [ 0.  0.  0. nan  0.]]
File not found:  rankshap_breast_cancer_K5
####################
Method:  rankshap 	Guarantee:  rank 	Alpha:  0.2
Max FWER (%)
[[16. 14. 14.  0.  2.]
 [ 0.  0.  0. nan  0.]]
####################
Method:  rankshap 	Guarantee:  set 	Alpha:  0.1
Max FWER (%)
[[2. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0.]]
####################
Method:  rankshap 	Guarantee:  set 	Alpha:  0.2
Max FWER (%)
[[16.  0.  6.  0.  0.]
 [ 4.  2.  2.  0.  0.]]
File not found:  sprtshap_bank_K5
File not found:  sprtshap_credit_K5
####################
Method:  sprtshap 	Guarantee:  rank 	Alpha:  0.1
Max FWER (%)
[[ 0.  0.  0.  0.  0.]
 [ 0. nan  0.  0. nan]]
File not found:  sprtshap_bank_K5
File not found:  sprtshap_breast_cancer_K5
File not found:  sprtshap_credit_K5
####################
Method:  sprtshap 	Guarantee:  rank 	Alpha:  0.2
Max FWER (%)
[[ 0.  0. 

In [6]:
# data_dir = join(dir_path, "Experiments", "Results", "Top_K", "rank", "alpha_"+str(0.2))
# fname = "sprtshap_census_K2"
# path = join(data_dir, fname)
# with open(path, "rb") as fp:
#     results = pickle.load(fp)
# # results.keys()
# results['x_indices']