In [1]:
import numpy as np
import pickle
import pathlib

from os.path import join, exists
path_to_file = str(pathlib.Path().resolve())
dir_path = join(path_to_file, "../../")

import sys
sys.path.append(join(dir_path, "HelperFiles"))

from helper import *


# SHAP Results

In [27]:
datasets = ["census", "bank", "brca", "credit", "breast_cancer"]
Ks = [2,5]
methods = ["rankshap", "sprtshap"]
guarantees = ["rank", "set"]
for method in methods:
    for K in Ks:
        for alpha in [0.1, 0.2]:
            max_mat = np.empty((len(Ks), len(datasets)))
            for i, guarantee in enumerate(guarantees):
                data_dir = join(dir_path, "Experiments", "Results", "Top_K", guarantee, "alpha_"+str(alpha)) 
                for j, dataset in enumerate(datasets):
                    max_mat[i,j] = np.nan
                    fname = method + "_" + dataset + "_K" + str(K) 
                    path = join(data_dir, fname)
                    if exists(path):
                        with open(path, "rb") as fp:
                            results = pickle.load(fp)
                        # fwers = results['fwers']
                        # try:
                        top_K_all = results['top_K']
                        rejection_idx = results['rejection_idx']
                        fwers_all = np.array([calc_fwer(top_K, rejection_idx=idx) for top_K, idx in zip(top_K_all, rejection_idx)])
                        relevant_idx = [len(idx)>=50*0.9 for idx in rejection_idx]
                        fwers = fwers_all[relevant_idx]
                        # if len(fwers)>=3 and len(fwers)<=15:
                        #     print(fname)
                        if len(fwers)>0:
                            max_fwer = np.max(fwers)
                            max_mat[i, j] = np.round(max_fwer*100).item()
            print("#"*20)
            print("Method: ", method, "\tK:", str(K), "\tAlpha:", alpha)

            print("Max FWER (%)")
            print(max_mat)


####################
Method:  rankshap 	K: 2 	Alpha: 0.1
Max FWER (%)
[[8. 6. 6. 4. 0.]
 [2. 2. 6. 2. 4.]]
####################
Method:  rankshap 	K: 2 	Alpha: 0.2
Max FWER (%)
[[16. 14. 14.  8. 10.]
 [16.  0. 10.  2. 12.]]
####################
Method:  rankshap 	K: 5 	Alpha: 0.1
Max FWER (%)
[[ 6. 10. 10.  4.  6.]
 [ 6. 10. 10.  4.  4.]]
####################
Method:  rankshap 	K: 5 	Alpha: 0.2
Max FWER (%)
[[14. 18. 20. 12. 20.]
 [14. 16. 20. 16.  4.]]
####################
Method:  sprtshap 	K: 2 	Alpha: 0.1
Max FWER (%)
[[ 0.  0. nan  0.  0.]
 [ 0.  0.  0.  0.  0.]]
####################
Method:  sprtshap 	K: 2 	Alpha: 0.2
Max FWER (%)
[[ 2.  2. nan  0.  4.]
 [ 0.  2.  0.  0.  0.]]
####################
Method:  sprtshap 	K: 5 	Alpha: 0.1
Max FWER (%)
[[nan nan nan nan  0.]
 [ 0.  0.  0.  0.  0.]]
####################
Method:  sprtshap 	K: 5 	Alpha: 0.2
Max FWER (%)
[[nan nan nan nan  0.]
 [ 8.  2.  2.  2.  0.]]


## LIME Results

In [35]:
method = "lime"
guarantee = "rank"
for alpha in [0.1, 0.2]:
    max_mat = np.empty((len(Ks), len(datasets)))
    data_dir = join(dir_path, "Experiments", "Results", "Top_K", guarantee, "alpha_"+str(alpha))
    for i, K in enumerate(Ks):
        for j, dataset in enumerate(datasets):
            max_mat[i,j] = np.nan
            fname = method + "_" + dataset + "_K" + str(K) 
            path = join(data_dir, fname)
            if exists(path):
                with open(path, "rb") as fp:
                    results = pickle.load(fp)
                top_K_all = results['top_K']
                # if top_K_all.shape[0]>=30:
                rejection_idx = results['rejection_idx']
                fwers_all = np.array([calc_fwer(top_K, rejection_idx=idx) for top_K, idx in zip(top_K_all, rejection_idx)])
                relevant_idx = [len(idx)>50*0.9 for idx in rejection_idx]
                fwers = fwers_all[relevant_idx]
                if len(fwers) > 0:
                    max_fwer = np.max(fwers)
                    max_mat[i, j] = np.round(max_fwer*100, 1)

    print("#"*20)
    print("Method: LIME", "\tAlpha: ", alpha)

    print("Max FWER (%)")
    print(max_mat)



####################
Method: LIME 	Alpha:  0.1
Max FWER (%)
[[ 0.  2.  2.  6. 16.]
 [nan  0. nan  0.  0.]]
####################
Method: LIME 	Alpha:  0.2
Max FWER (%)
[[ 2.  0.  0.  8.  2.]
 [nan  0. nan  0.  0.]]


In [38]:
alpha = 0.1
dataset = "breast_cancer"
data_dir = join(dir_path, "Experiments", "Results", "Top_K", guarantee, "alpha_"+str(alpha))
K = 2
fname = method + "_" + dataset + "_K" + str(K) 
path = join(data_dir, fname)

with open(path, "rb") as fp:
    results = pickle.load(fp)
top_K_all = results['top_K']
# if top_K_all.shape[0]>=30:
rejection_idx = results['rejection_idx']
fwers_all = np.array([calc_fwer(top_K, rejection_idx=idx) for top_K, idx in zip(top_K_all, rejection_idx)])


array([0.  , 0.  , 0.16, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  ])

In [45]:
results['x_indices'][2]
# asdf asdf 

np.int64(3)